#服务器端口
server:
  port : 8088

#mysql配置
spring:
  application:
    name: base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://192.168.18.128:3306/mytest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true
    username : root
    password: 1903@heBut.
#redis
  redis:
    host: 192.168.18.128
    port: 6379
    password: 1903@heBut.
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  activemq:
    broker-url:

#slf4j#logging:
#默认读取配置文件地址，classpsth:的logback-spring.xml文件
#config: classpath:logback-spring.xml

## token

#swaqgger自定义
swagger:
  # 是否启用
  enable: true
  base:
    # 扫描的包，多个包使用逗号隔开
    package: com.hebut.base.controller
  contact:
    email: 1371491803@qq.com
    name: cxc
    url: 1371491803@qq.com
  description: 风电场管理
  title: ${spring.application.name} API Document
  url: localhost:${server.port}/doc.html
  version: 1.0.0
#knife4j作为swagger增强,地址：localhoet:8088/doc.html
knife4j:
  enable: ${swagger.enable}
  openapi:
    title: Knife4j官方文档

